tracing:
  serviceName: pp-gin
rest:
  server:
    host: localhost
    port: 8080
    swaggerUrl: /swagger
    metricsUrl: /metrics
    readTimeoutSec: 5
    writeTimeoutSec: 10
    shutdownTimeoutSec: 20
  client:
    retriesMax: 2
    timeoutSec: 10
db:
  host: localhost
  port: 5432
  user: pg
  password: pg
  dbName: pg
  maxConnections: 10
  maxIdleConnections: 2
cache:
  defaultEntityCount: 20
logging:
  level: 6 # 6:trace
  timestampFormat: 15.04.05 02.01.2006.000000000
  default: true
scheduler:
  enabled: true
  periodSec: 5
  jobLimit: 10000